### ISSUE TITLE
Calling `octave_value` constructor explicitly is not necessary.

### ISSUE THREAD

**Issue by siko1056** [Abdallah-Elshamy/Octave-GSoC-JSON#10]
Two small fixes, making the code more readable:

https://github.com/Abdallah-Elshamy/Octave-GSoC-JSON/blob/58fa7a2ea0e49ffdb2cc9e3bf2fa8a5ebc0d39b2/jsondecode.cc#L408

and

https://github.com/Abdallah-Elshamy/Octave-GSoC-JSON/blob/58fa7a2ea0e49ffdb2cc9e3bf2fa8a5ebc0d39b2/jsondecode.cc#L412

**Comment by Abdallah-Elshamy** [comment]
Fixed in 26a7b74
