### ISSUE TITLE
Unit tests ASCII conversion

### ISSUE THREAD

**Issue by siko1056** [Abdallah-Elshamy/Octave-GSoC-JSON#11]
As we discussed last Friday, we should consider proper treatment of all ASCII characters in both JSON conversion directions.  According to [Wikipedia](https://en.wikipedia.org/wiki/ASCII) this should be all:

```
\0\a\b\t\n\v\f\r !"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~
```

Own experiments with Matlab showed me, that basically escaping with `\` happends, e.g. `\n` becomes `\\n`, etc.

**Comment by Abdallah-Elshamy** [comment]
I added a note about this in the function documentation. If you have any comments, please let me know

https://github.com/Abdallah-Elshamy/Octave-GSoC-JSON/blob/5d0bacfa97db2bac1d336c79ae6444c32444708c/jsonencode.cc#L443-L444

**Comment by siko1056** [comment]
Basically, this item is a bit more complex.  We need also test for `\r`, which becomes becomes `\\r`, and some more.  Same for the decode direction.  In Matlab R2020b for example:

```matlab
>> jsonencode ('\0\n\r')
ans =    '"\\0\\n\\r"'

>> jsondecode ('"\0\n\r"')
Error using jsondecode
JSON syntax error at line 1, column 2 (character 2): escape character '\0' is not valid.
 
>> jsondecode ('"\\0\\n\\r"')
ans =    '\0\n\r'
```

Maybe we schedule this for after our Thursday meeting.

**Comment by siko1056** [comment]
Done as discussed.
