### ISSUE TITLE
Merge with Octave: configure.ac

### ISSUE THREAD

**Issue by siko1056** [Abdallah-Elshamy/Octave-GSoC-JSON#12]
Just as a reminder in extension to [our discussion on the Octave maintainers mailing-list](https://lists.gnu.org/archive/html/octave-maintainers/2020-05/msg00120.html) I finally figured out a working `configure.ac` check for RapidJSON, especially for a newer version by checking for the `rapidjson/cursorstreamwrapper.h` header.

```patch
diff -r 652a675c0916 configure.ac
--- a/configure.ac	Mon Aug 03 11:13:26 2020 -0400
+++ b/configure.ac	Wed Aug 12 12:49:26 2020 +0900
@@ -1331,6 +1331,22 @@ OCTAVE_CHECK_LIB(pcre, PCRE,
   ],
   [libpcre], [REQUIRED])

+### Check for RapidJSON header only library.
+
+AC_LANG_PUSH([C++])
+AC_CHECK_HEADER([rapidjson/rapidjson.h], [have_rapidjson=yes], [have_rapidjson=no
+  rapid_json_warning="RapidJSON library not found.  Octave will not be able to read or write JSON files."])
+if test "$have_rapidjson" = yes; then
+  AC_CHECK_HEADER([rapidjson/cursorstreamwrapper.h], [have_rapidjson=yes], [have_rapidjson=no
+    rapid_json_warning="RapidJSON 1.1.0 or older found, but latest development version needed.  Octave will not be able to read or write JSON files."])
+fi
+if test "$have_rapidjson" = yes; then
+  AC_DEFINE(HAVE_RAPIDJSON, 1, [Define to 1 if RapidJSON is available.])
+else
+  OCTAVE_CONFIGURE_WARNING([rapid_json_warning])
+fi
+AC_LANG_POP([C++])
+
 ### Check for readline library.

 OCTAVE_ENABLE_READLINE
```

Using this patch for merging with the Octave sources, can you wrap the code in the main function of `jsondecode.cc` and `jsonencode.cc` with something like this for `HAVE_RAPIDJSON`

https://hg.savannah.gnu.org/hgweb/octave/file/652a675c0916/libinterp/dldfcn/audioread.cc#l82
https://hg.savannah.gnu.org/hgweb/octave/file/652a675c0916/libinterp/dldfcn/audioread.cc#l192

**Comment by Abdallah-Elshamy** [comment]
That's a clever solution. I think it suits our purpose perfectly. 

I wrapped the code in e1795da and e122ff3. 

Please, let me know if there is any comments.

Thanks for your efforts.

**Comment by siko1056** [comment]
Only the last `#if ... #else ... #endif` is necessary.  Please revert those many other statements.  Most compilers are clever enough to detect that those functions are never called and don't compile them :wink:

**Comment by Abdallah-Elshamy** [comment]
I edited the commits. Now 3fd5f06 and 3353245 contain only the last `#if ... #else ... #endif`

Please, let me know if there is any comments.

**Comment by siko1056** [comment]
Item done.
